---
- hosts: all
  become: yes

  tasks:
    - name: install base packages
      apt:
        name:
          - aptitude
          - awscli
          - curl    # required by geerlingguy.jenkins
          - direnv
          - git
          - neovim
        state: latest

    # this is pulling in the wrong version of OpenJDK
    # as far as I know, we need version 8
    #
    # ubuntu@ip-172-31-29-171:~/interview-liatrio-2018/technical-exercise/ansible$ java -version
    # openjdk version "10.0.2" 2018-07-17
    # OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1)
    # OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.1, mixed mode)

    - include_role:
        name: geerlingguy.jenkins

    - name: update apt-get if needed
      apt:
        update_cache: yes
