---
- hosts: all
  become: true

  # TODO fix this
  #  vars:
  #    jenkins_admin_password: "fubar"
  #    nexus_admin_password: "fubar"

    #jenkins_admin_password:  {{ lookup('env', 'JENKINS_ADMIN_PASSWORD') }}
    #nexus_admin_password:  {{ lookup('env', 'NEXUS_ADMIN_PASSWORD') }}

  roles:
    - timcondit.coretools
    - timcondit.java
    - ansible-thoteam.nexus3-oss
    - geerlingguy.jenkins
