---
- hosts: all
  become: true

  vars:
    jenkins_plugins: [
      'build-pipeline-plugin',
      'git-client',
      'git',
      'github',
      'greenballs',
      'nexus-jenkins-plugin',
      #      'pipeline-plugin'
    ]

    #jenkins_admin_password:  {{ lookup('env', 'JENKINS_ADMIN_PASSWORD') }}
    #nexus_admin_password:  {{ lookup('env', 'NEXUS_ADMIN_PASSWORD') }}

  roles:
    - timcondit.coretools
    - timcondit.java
    - ansible-thoteam.nexus3-oss
    - geerlingguy.jenkins
